<?php if (!defined('IN_PHPBB')) exit; $this->_tpl_include('styleswitcher.html'); ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="<?php echo (isset($this->_rootref['S_CONTENT_DIRECTION'])) ? $this->_rootref['S_CONTENT_DIRECTION'] : ''; ?>" lang="<?php echo (isset($this->_rootref['S_USER_LANG'])) ? $this->_rootref['S_USER_LANG'] : ''; ?>" xml:lang="<?php echo (isset($this->_rootref['S_USER_LANG'])) ? $this->_rootref['S_USER_LANG'] : ''; ?>">
<head>

<meta http-equiv="content-type" content="text/html; charset=<?php echo (isset($this->_rootref['S_CONTENT_ENCODING'])) ? $this->_rootref['S_CONTENT_ENCODING'] : ''; ?>" />
<meta http-equiv="content-style-type" content="text/css" />
<meta http-equiv="content-language" content="<?php echo (isset($this->_rootref['S_USER_LANG'])) ? $this->_rootref['S_USER_LANG'] : ''; ?>" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="resource-type" content="document" />
<meta name="distribution" content="global" />
<meta name="copyright" content="2000, 2002, 2005, 2007 phpBB Group" />
<meta name="keywords" content="" />
<meta name="description" content="" />
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE7" />
<?php echo (isset($this->_rootref['META'])) ? $this->_rootref['META'] : ''; ?>

<title><?php echo (isset($this->_rootref['SITENAME'])) ? $this->_rootref['SITENAME'] : ''; ?> &bull; <?php if ($this->_rootref['S_IN_MCP']) {  echo ((isset($this->_rootref['L_MCP'])) ? $this->_rootref['L_MCP'] : ((isset($user->lang['MCP'])) ? $user->lang['MCP'] : '{ MCP }')); ?> &bull; <?php } else if ($this->_rootref['S_IN_UCP']) {  echo ((isset($this->_rootref['L_UCP'])) ? $this->_rootref['L_UCP'] : ((isset($user->lang['UCP'])) ? $user->lang['UCP'] : '{ UCP }')); ?> &bull; <?php } echo (isset($this->_rootref['PAGE_TITLE'])) ? $this->_rootref['PAGE_TITLE'] : ''; ?></title>

<?php $this->_tpl_include('../../../rokbb3.php'); $this->_tpl_include('refraction.php'); ?>


<!--
	phpBB style name: refraction
	Based on style:   prosilver (this is the default phpBB3 style)
	Original author:  Tom Beddard ( http://www.subBlue.com/ )
	Modified by: RocketTheme, LLC (C) Copyright. All rights reserved.    
	
	NOTE: This page was generated by phpBB, the free open-source bulletin board package.
	      The phpBB Group is not responsible for the content of this page and forum. For more information
	      about phpBB please visit http://www.phpbb.com
-->


<script type="text/javascript">
// <![CDATA[
	var jump_page = '<?php echo ((isset($this->_rootref['LA_JUMP_PAGE'])) ? $this->_rootref['LA_JUMP_PAGE'] : ((isset($this->_rootref['L_JUMP_PAGE'])) ? addslashes($this->_rootref['L_JUMP_PAGE']) : ((isset($user->lang['JUMP_PAGE'])) ? addslashes($user->lang['JUMP_PAGE']) : '{ JUMP_PAGE }'))); ?>:';
	var on_page = '<?php echo (isset($this->_rootref['ON_PAGE'])) ? $this->_rootref['ON_PAGE'] : ''; ?>';
	var per_page = '<?php echo (isset($this->_rootref['PER_PAGE'])) ? $this->_rootref['PER_PAGE'] : ''; ?>';
	var base_url = '<?php echo (isset($this->_rootref['A_BASE_URL'])) ? $this->_rootref['A_BASE_URL'] : ''; ?>';
	var style_cookie = 'phpBBstyle';
	var style_cookie_settings = '<?php echo (isset($this->_rootref['A_COOKIE_SETTINGS'])) ? $this->_rootref['A_COOKIE_SETTINGS'] : ''; ?>';
	var onload_functions = new Array();
	var onunload_functions = new Array();

	<?php if ($this->_rootref['S_USER_PM_POPUP']) {  ?>

		if (<?php echo (isset($this->_rootref['S_NEW_PM'])) ? $this->_rootref['S_NEW_PM'] : ''; ?>)
		{
			var url = '<?php echo (isset($this->_rootref['UA_POPUP_PM'])) ? $this->_rootref['UA_POPUP_PM'] : ''; ?>';
			window.open(url.replace(/&amp;/g, '&'), '_phpbbprivmsg', 'height=225,resizable=yes,scrollbars=yes, width=400');
		}
	<?php } ?>


	/**
	* Find a member
	*/
	function find_username(url)
	{
		popup(url, 760, 570, '_usersearch');
		return false;
	}

	/**
	* New function for handling multiple calls to window.onload and window.unload by pentapenguin
	*/
	window.onload = function()
	{
		for (var i = 0; i < onload_functions.length; i++)
		{
			eval(onload_functions[i]);
		}
	}

	window.onunload = function()
	{
		for (var i = 0; i < onunload_functions.length; i++)
		{
			eval(onunload_functions[i]);
		}
	}

// ]]>
</script>

<script type="text/javascript" src="<?php echo (isset($this->_rootref['T_TEMPLATE_PATH'])) ? $this->_rootref['T_TEMPLATE_PATH'] : ''; ?>/styleswitcher.js"></script>
<script type="text/javascript" src="<?php echo (isset($this->_rootref['T_TEMPLATE_PATH'])) ? $this->_rootref['T_TEMPLATE_PATH'] : ''; ?>/forum_fn.js"></script>

<link href="<?php echo (isset($this->_rootref['T_THEME_PATH'])) ? $this->_rootref['T_THEME_PATH'] : ''; ?>/print.css" rel="stylesheet" type="text/css" media="print" title="printonly" />
<link href="<?php echo (isset($this->_rootref['T_STYLESHEET_LINK'])) ? $this->_rootref['T_STYLESHEET_LINK'] : ''; ?>" rel="stylesheet" type="text/css" media="screen, projection" />

<link href="<?php echo (isset($this->_rootref['T_THEME_PATH'])) ? $this->_rootref['T_THEME_PATH'] : ''; ?>/normal.css" rel="stylesheet" type="text/css" title="A" />
<link href="<?php echo (isset($this->_rootref['T_THEME_PATH'])) ? $this->_rootref['T_THEME_PATH'] : ''; ?>/medium.css" rel="alternate stylesheet" type="text/css" title="A+" />
<link href="<?php echo (isset($this->_rootref['T_THEME_PATH'])) ? $this->_rootref['T_THEME_PATH'] : ''; ?>/large.css" rel="alternate stylesheet" type="text/css" title="A++" />

<?php if ($this->_rootref['S_CONTENT_DIRECTION'] == ('rtl')) {  ?>

	<link href="<?php echo (isset($this->_rootref['T_THEME_PATH'])) ? $this->_rootref['T_THEME_PATH'] : ''; ?>/bidi.css" rel="stylesheet" type="text/css" media="screen, projection" />
<?php } ?>


<script type="text/javascript" src="<?php echo (isset($this->_rootref['T_TEMPLATE_PATH'])) ? $this->_rootref['T_TEMPLATE_PATH'] : ''; ?>/rt_js/mootools-release-1.11.js"></script>
<script type="text/javascript" src="<?php echo (isset($this->_rootref['T_TEMPLATE_PATH'])) ? $this->_rootref['T_TEMPLATE_PATH'] : ''; ?>/rt_js/rokutils.js"></script>
<?php if ($this->_rootref['ENABLE_REF_FONTSPANS']) {  ?>

<script type="text/javascript" src="<?php echo (isset($this->_rootref['T_TEMPLATE_PATH'])) ? $this->_rootref['T_TEMPLATE_PATH'] : ''; ?>/rt_js/rokfonts.js"></script>
<?php } ?>

<script type="text/javascript" src="<?php echo (isset($this->_rootref['T_TEMPLATE_PATH'])) ? $this->_rootref['T_TEMPLATE_PATH'] : ''; ?>/rt_js/rokmoomenu.js"></script>
<script type="text/javascript" src="<?php echo (isset($this->_rootref['T_TEMPLATE_PATH'])) ? $this->_rootref['T_TEMPLATE_PATH'] : ''; ?>/rt_js/mootools.bgiframe.js"></script>
<?php if ($this->_rootref['ENABLE_REF_INFO']) {  ?>

<script type="text/javascript" src="<?php echo (isset($this->_rootref['T_TEMPLATE_PATH'])) ? $this->_rootref['T_TEMPLATE_PATH'] : ''; ?>/rt_js/roknewsflash-packed.js"></script>
<?php } ?>


                <style type="text/css">
    <!--
	body.iehandle #main-background {background-attachment:<?php if ($this->_rootref['REF_BG_FIXED']) {  echo (isset($this->_rootref['REF_BG_FIXED'])) ? $this->_rootref['REF_BG_FIXED'] : ''; } else { ?>scroll<?php } ?>;}
	div.wrapper { margin: 0 auto; <?php if ($this->_rootref['REF_WIDTH']) {  ?>width:<?php echo (isset($this->_rootref['REF_WIDTH'])) ? $this->_rootref['REF_WIDTH'] : ''; ?>px;<?php } else { ?>width:979px;<?php } ?>padding:0;}
	#inset-block-left { width:0px;padding:0;}
	#inset-block-right { width:0px;padding:0;}
	#maincontent-block { margin-right:0px;margin-left:0px;}
	#main-body ul.menu li a:hover, ul.roknewspager-numbers li.active, .feature-block .feature-desc, #horiz-menu li.active .link span, #horiz-menu li:hover .link span, #horiz-menu li.sfHover .link span, #horiz-menu li:hover li:hover .link span, #horiz-menu li:hover li:hover li:hover .link span, #horiz-menu li.sfHover li.sfHover .link span, #horiz-menu li.sfHover li.sfHover li.sfHover .link span, #showcase-section, .side-mod h3, #searchmod-surround h3, #main-body ul.menu li a:hover, ul.roknewspager-numbers li.active, a:hover, #featuremodules,#cp-main h2,#tabs .activetab a:hover span,#minitabs li.activetab a, #minitabs li.activetab a:hover {color: <?php if ($this->_rootref['REF_SHOWCASE_TEXT']) {  echo (isset($this->_rootref['REF_SHOWCASE_TEXT'])) ? $this->_rootref['REF_SHOWCASE_TEXT'] : ''; } else { ?>#dddddd<?php } ?>;}
	#showcase-section .feature-block .feature-title,li.header dt, li.header dd,li.header dt a:link,li.header dt a:visited,.post:target .content {color:<?php if ($this->_rootref['REF_SHOWCASE_TITLE']) {  echo (isset($this->_rootref['REF_SHOWCASE_TITLE'])) ? $this->_rootref['REF_SHOWCASE_TITLE'] : ''; } else { ?>#d2de00<?php } ?>;}
	#showcase-section a,a:hover,a.forumtitle:active,a.forumtitle:hover,a.topictitle:active,a.topictitle:hover,a.left:hover,a.button1:hover, input.button1:hover, input.button3:hover, a.button2:hover, input.button2:hover,.inputbox:focus,.inputbox:hover {color: <?php if ($this->_rootref['REF_SHOWCASE_LINK']) {  echo (isset($this->_rootref['REF_SHOWCASE_LINK'])) ? $this->_rootref['REF_SHOWCASE_LINK'] : ''; } else { ?>#A4AD2B<?php } ?>;}
	.variation-chooser input, #mainbody-overlay, #searchmod-surround .inputbox, form.search_result input.button, form.poll input.button, form.form-login .inputbox, form.form-login input.button, form.log input.button, #bottom, form#emailForm input.button, #copyright, #top-button a, input#search_searchword.inputbox, form.search_result legend, .contact_email .inputbox, .readon-wrap1 input.button, input#email.required, .logo-module, .footer-mod,#message-box textarea,#navigation #active-subsection a {color: <?php if ($this->_rootref['REF_BODY_TEXT']) {  echo (isset($this->_rootref['REF_BODY_TEXT'])) ? $this->_rootref['REF_BODY_TEXT'] : ''; } else { ?>#aaaaaa<?php } ?>;}
	#roktwittie .status .header .nick, .search-results-full span.highlight, #main-background div.articleListingImage img, #main-background div.sbArticleImage img  {background: <?php if ($this->_rootref['REF_BODY_LINK']) {  echo (isset($this->_rootref['REF_BODY_LINK'])) ? $this->_rootref['REF_BODY_LINK'] : ''; } else { ?>#A4AD2B<?php } ?>;}
	a,a:link,a:visited, .contentheading, #horiz-menu li:hover li .link span, #horiz-menu li:hover li:hover li .link span, #horiz-menu li.sfHover li .link span, #horiz-menu li.sfHover li.sfHover li .link span, .componentheading span, .roktabs-links li.active, .side-mod h3 span, .showcase-panel h3 span, #featuremodules h3,#newsflash ul,.postprofile strong,.pagination span strong,.pagination span a, .pagination span a:link, .pagination span a:visited, .pagination span a:active,.inputbox,#tabs .activetab a span, #navigation #active-subsection a:hover,#navigation a:hover,#cp-main .panel li.header dd, #cp-main .panel li.header dt,dt label,h3   {color: <?php if ($this->_rootref['REF_BODY_LINK']) {  echo (isset($this->_rootref['REF_BODY_LINK'])) ? $this->_rootref['REF_BODY_LINK'] : ''; } else { ?>#A4AD2B<?php } ?>;}
    -->
    
    <?php if ($this->_rootref['REF_MENUPOSITION'] == (left) || $this->_rootref['REF_MENUPOSITION'] == (right)) {  ?>

#postingbox .autowidth {width: 90% !important; }
	#postingbox .column2 { width: 75%; margin-top:-75px; position: relative;}
	#postingbox .column1 { width: 70%;position: relative; z-index:10000;}
	#postingbox fieldset.fields1 dd { margin-left: 15em;}
	#colour_palette dd { margin-left: 6em !important;}
	<?php } if ($this->_rootref['REF_MENUPOSITION'] == (full)) {  ?>

	ul.topiclist dt {width:57%;}
	dd.lastpost {width:20%;}
	<?php } if ($this->_rootref['AVATAR_POSITION'] == (left)) {  ?>

	.postprofile {float: left; border: 0px; margin-left: -6px;}
	.postbody {float: right;}
	ul.profile-icons {margin-right: 40px;}
	<?php } ?>

	
  </style>

<!--[if IE 7]>
<link href="<?php echo (isset($this->_rootref['T_THEME_PATH'])) ? $this->_rootref['T_THEME_PATH'] : ''; ?>/template_ie7.css" rel="stylesheet" type="text/css" />	
<![endif]-->	


<!--[if lte IE 6]>
<link href="<?php echo (isset($this->_rootref['T_THEME_PATH'])) ? $this->_rootref['T_THEME_PATH'] : ''; ?>/template_ie6.css" rel="stylesheet" type="text/css" />
<script src="<?php echo (isset($this->_rootref['T_TEMPLATE_PATH'])) ? $this->_rootref['T_TEMPLATE_PATH'] : ''; ?>/rt_js/DD_belatedPNG.js"></script>
<script type="text/javascript">
	var pngClasses = ['.png', '.menutop li.active a', '.readon1-l', '.readon1-m', '.readon1-r', '#roktwittie .status .header', '.blog .roknewspager-div', '.control-prev', '.control-next', '.control-prev-hover', '#main-body ul.menu li', '.roknewspager-div', '#main-body ul.menu li a', '.roknewspager-pages', '.roknewspager-prev-disabled', '.roknewspager-prev', '.roknewspager-next-disabled', '.roknewspager-numbers', '.roknewspager-next', '#roktwittie .roktwittie-surround', 'a.sbDisqusCounter', 'div.superBloggerTop', 'div.sbRating', 'div.sbAuthorBlock', '#disqus_thread', 'div.superBloggerTop a', 'div.superBloggerTop img', '.sbAuthorLatestTweets ul li', '.sbAuthorLatest ul li', 'span.ob_commentOut', '#roksearch_results .roksearch_row_btm', '#roksearch_results .roksearch_header', '#roksearch_results', '#roksearch_results .roksearch_odd', '#roksearch_results .roksearch_even', '#roksearch_results .roksearch_even-hover', '#roksearch_results .roksearch_odd-hover', 'pre', 'blockquote', 'th.sectiontableheader', '.roktabs-links ul li span', '.roktabs-links ul li.active', '.roktabs-wrapper .arrow-next', '.roktabs-wrapper .arrow-prev', '.active-arrows', '.icon', '.forabg', '.forumbg', 'ul.forums', 'ul.topics', 'li.row', 'img', 'a', 'li', '#keywords', 'span','input','.post_bg','.panel','.inputbox'];
	
	pngClasses.each(function(fixMePlease) {
		DD_belatedPNG.fix(fixMePlease);
	});
	
</script>
<![endif]-->
   <script type="text/javascript">
		window.templatePath = '<?php echo (isset($this->_rootref['THEME_PATH'])) ? $this->_rootref['THEME_PATH'] : ''; ?>';
		window.uri = '<?php echo (isset($this->_rootref['U_INDEX'])) ? $this->_rootref['U_INDEX'] : ''; ?>';
		window.currentStyle = '<?php echo (isset($this->_rootref['REF_PRESET_STYLE'])) ? $this->_rootref['REF_PRESET_STYLE'] : ''; ?>';
		
<?php if ($this->_rootref['ENABLE_REF_FONTSPANS']) {  ?>	
window.addEvent('domready', function() {
		var modules = ['side-mod', 'showcase-panel'];
		var header = ['h3','h1'];
		RokBuildSpans(modules, header);
	});
<?php } ?>


window.addEvent('domready', function() {
    	new Rokmoomenu($E('ul.menutop '), {
    		bgiframe: false,
    		delay: 500,
    		verhor: true,
    		animate: {
    			props: ['height'],
    			opts: {
    				duration: 500,
    				fps: 100,
    				transition: Fx.Transitions.Quad.easeOut
    			}
    		},
    		bg: {
    			enabled: true,
    			overEffect: {
    				duration: 500,
    				transition: Fx.Transitions.Sine.easeOut
    			},
    			outEffect: {
    				duration: 600,
    				transition: Fx.Transitions.Sine.easeOut
    			}
    		},
    		submenus: {
    			enabled: true,
    			opacity: 0.9,
    			overEffect: {
    				duration: 50,
    				transition: Fx.Transitions.Expo.easeOut
    			},
    			outEffect: {
    				duration: 600,
    				transition: Fx.Transitions.Sine.easeIn
    			},
    			offsets: {
    				top: 3,
    				right: 1,
    				bottom: 0,
    				left: 1
    			}
    		}
    	});
    });
  </script>
		      
		      <?php if ($this->_rootref['REF_PRESET_STYLE'] == ('style2') || $this->_rootref['REF_PRESET_STYLE'] == ('style10')) {  ?>

<script type="text/javascript">
// <![CDATA[
window.addEvent('domready', function() {
  var newImagePath = '<?php echo (isset($this->_rootref['ROOT_PATH'])) ? $this->_rootref['ROOT_PATH'] : ''; ?>/styles/refraction_light/imageset/'; // remember to add the ending forward slash
  var classToSearch = '.icon';
  
  var els = $$(classToSearch);
  if (els.length) {
    els.each(function(el) {
      var bg = el.getStyle('background-image'), newBg, imgSource;
      bg = bg.replace('")', '').replace(")", '');
      var tmp = bg.split('/');
      imgSource = tmp[tmp.length - 1];
      el.setStyle('background-image', 'url('+newImagePath+imgSource+')');     
    });
  }
});
// ]]>
</script>
	<?php } ?>

	
</head>

<body id="<?php if ($this->_rootref['REF_FONTFACE']) {  echo (isset($this->_rootref['REF_FONTFACE'])) ? $this->_rootref['REF_FONTFACE'] : ''; } else { ?>ff-refraction<?php } ?>" class="<?php if ($this->_rootref['REF_PRESET_STYLE']) {  echo (isset($this->_rootref['REF_PRESET_STYLE'])) ? $this->_rootref['REF_PRESET_STYLE'] : ''; } else { ?>style1<?php } if ($this->_rootref['REF_BG_STYLE']) {  ?> <?php echo (isset($this->_rootref['REF_BG_STYLE'])) ? $this->_rootref['REF_BG_STYLE'] : ''; } else { ?> bgstyle1<?php } if ($this->_rootref['REF_OVERLAY_STYLE']) {  ?> <?php echo (isset($this->_rootref['REF_OVERLAY_STYLE'])) ? $this->_rootref['REF_OVERLAY_STYLE'] : ''; } else { ?> dark<?php } ?> iehandle section-<?php echo (isset($this->_rootref['SCRIPT_NAME'])) ? $this->_rootref['SCRIPT_NAME'] : ''; ?> <?php echo (isset($this->_rootref['S_CONTENT_DIRECTION'])) ? $this->_rootref['S_CONTENT_DIRECTION'] : ''; ?>">


<div id="main-background">
	

			<!--Begin Header-->
						<div id="header-overlay" class="png">
				<div class="wrapper">
					<!--Begin Logo-->
										<a href="<?php echo (isset($this->_rootref['U_INDEX'])) ? $this->_rootref['U_INDEX'] : ''; ?>" id="logo" class="png"></a>
										<!--End Logo-->
					<!--Begin Horizontal Menu-->
										<div id="horiz-menu-surround">
					<?php if ($this->_rootref['S_ALLOW_JMENU']) {  ?>

						<div id="horiz-menu" class="moomenu png">
										
																<?php if ($this->_rootref['S_USER_LOGGED_IN']) {  ?>

							<?php echo (isset($this->_rootref['T_JOOMLA_MENU_REG'])) ? $this->_rootref['T_JOOMLA_MENU_REG'] : ''; ?>

							<?php } else { ?>

							<?php echo (isset($this->_rootref['T_JOOMLA_MENU'])) ? $this->_rootref['T_JOOMLA_MENU'] : ''; ?>

							<?php } } else { ?>

							
							<div id="horiz-menu" class="moomenu png">
								

																<ul class="menutop png">
<li<?php echo (isset($this->_rootref['U_INDEX_STYLE'])) ? $this->_rootref['U_INDEX_STYLE'] : ''; ?>><a class="topdaddy link" href="<?php echo (isset($this->_rootref['U_INDEX'])) ? $this->_rootref['U_INDEX'] : ''; ?>" accesskey="h"><span><?php echo ((isset($this->_rootref['L_INDEX'])) ? $this->_rootref['L_INDEX'] : ((isset($user->lang['INDEX'])) ? $user->lang['INDEX'] : '{ INDEX }')); ?></span></a></li>

<?php if (! $this->_rootref['S_IS_BOT'] && $this->_rootref['S_USER_LOGGED_IN']) {  ?>


				<li<?php echo (isset($this->_rootref['U_PROFILE_STYLE'])) ? $this->_rootref['U_PROFILE_STYLE'] : ''; ?>><a class="topdaddy link" href="<?php echo (isset($this->_rootref['U_PROFILE'])) ? $this->_rootref['U_PROFILE'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_PROFILE'])) ? $this->_rootref['L_PROFILE'] : ((isset($user->lang['PROFILE'])) ? $user->lang['PROFILE'] : '{ PROFILE }')); ?>" accesskey="u"><span><?php echo ((isset($this->_rootref['L_PROFILE'])) ? $this->_rootref['L_PROFILE'] : ((isset($user->lang['PROFILE'])) ? $user->lang['PROFILE'] : '{ PROFILE }')); ?></span></a></li>
<?php if ($this->_rootref['S_DISPLAY_PM']) {  ?><li<?php echo (isset($this->_rootref['U_PRIVATEMSGS_STYLE'])) ? $this->_rootref['U_PRIVATEMSGS_STYLE'] : ''; ?>><a  class="topdaddy link"  href="<?php echo (isset($this->_rootref['U_PRIVATEMSGS'])) ? $this->_rootref['U_PRIVATEMSGS'] : ''; ?>"><span><?php echo (isset($this->_rootref['PRIVATE_MESSAGE_INFO'])) ? $this->_rootref['PRIVATE_MESSAGE_INFO'] : ''; ?></span></a></li><?php } } ?>	


<li<?php echo (isset($this->_rootref['U_FAQ_STYLE'])) ? $this->_rootref['U_FAQ_STYLE'] : ''; ?>><a  class="topdaddy link"  href="<?php echo (isset($this->_rootref['U_FAQ'])) ? $this->_rootref['U_FAQ'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_FAQ_EXPLAIN'])) ? $this->_rootref['L_FAQ_EXPLAIN'] : ((isset($user->lang['FAQ_EXPLAIN'])) ? $user->lang['FAQ_EXPLAIN'] : '{ FAQ_EXPLAIN }')); ?>"><span><?php echo ((isset($this->_rootref['L_FAQ'])) ? $this->_rootref['L_FAQ'] : ((isset($user->lang['FAQ'])) ? $user->lang['FAQ'] : '{ FAQ }')); ?></span></a></li>
				<?php if (! $this->_rootref['S_IS_BOT']) {  if (! $this->_rootref['S_USER_LOGGED_IN']) {  ?><li<?php echo (isset($this->_rootref['U_REGISTER_STYLE'])) ? $this->_rootref['U_REGISTER_STYLE'] : ''; ?>><a class="topdaddy link" href="<?php echo (isset($this->_rootref['U_REGISTER'])) ? $this->_rootref['U_REGISTER'] : ''; ?>"><span><?php echo ((isset($this->_rootref['L_REGISTER'])) ? $this->_rootref['L_REGISTER'] : ((isset($user->lang['REGISTER'])) ? $user->lang['REGISTER'] : '{ REGISTER }')); ?></span></a></li><?php } ?>

					<li<?php echo (isset($this->_rootref['U_LOGIN_LOGOUT_STYLE'])) ? $this->_rootref['U_LOGIN_LOGOUT_STYLE'] : ''; ?>><a  class="topdaddy link"  href="<?php echo (isset($this->_rootref['U_LOGIN_LOGOUT'])) ? $this->_rootref['U_LOGIN_LOGOUT'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_LOGIN_LOGOUT'])) ? $this->_rootref['L_LOGIN_LOGOUT'] : ((isset($user->lang['LOGIN_LOGOUT'])) ? $user->lang['LOGIN_LOGOUT'] : '{ LOGIN_LOGOUT }')); ?>" accesskey="l"><span><?php echo ((isset($this->_rootref['L_LOGIN_LOGOUT'])) ? $this->_rootref['L_LOGIN_LOGOUT'] : ((isset($user->lang['LOGIN_LOGOUT'])) ? $user->lang['LOGIN_LOGOUT'] : '{ LOGIN_LOGOUT }')); ?></span></a></li>
				<?php } ?>


</ul>
					<?php } ?>

										</div>
					</div>
										<!--End Horizontal Menu-->
				</div>
			</div>
						<!--End Header-->
		
			<!--Begin Main Body-->
			<div id="mainbody-overlay" class="png"><div id="mainbody-overlay2" class="png">
				<div class="wrapper">
					<div id="main-body">
						<div id="main-body-surround">
							<!--Begin Main Content Block-->
							<div id="main-content" class="<?php if ($this->_rootref['REF_MENUPOSITION'] == (left)) {  ?>s<?php } else { ?>x<?php } ?>-c-<?php if ($this->_rootref['REF_MENUPOSITION'] == (right)) {  ?>s<?php } else { ?>x<?php } ?>">
							    <div class="colmask leftmenu">
							        <div class="colmid">
	    					    	    <div class="colright">
	        						        <!--Begin col1wrap -->    
	            						    <div class="col1wrap">
	            						        <div class="col1pad">
	            						            <div class="col1">
	                    						        <div id="maincol2">
	                    									<div class="maincol2-padding">
													<?php if ($this->_rootref['ENABLE_REF_INFO']) {  ?>

													<div id="newsflash-bar" class="png">
		                    										<script type="text/javascript">
	window.addEvent('domready', function() {
		var x = new RokNewsFlash('newsflash', {
			controls: true,
			delay: 2500,
			duration: 600,
			blankimage: '<?php echo (isset($this->_rootref['T_THEME_PATH'])) ? $this->_rootref['T_THEME_PATH'] : ''; ?>/images/blank.png'
		});
	});
</script>
<div id="newsflash" class="roknewsflash">
    <span class="flashing">Board info:</span>
    <ul>
	<li><?php if ($this->_rootref['BIRTHDAY_LIST']) {  echo ((isset($this->_rootref['L_CONGRATULATIONS'])) ? $this->_rootref['L_CONGRATULATIONS'] : ((isset($user->lang['CONGRATULATIONS'])) ? $user->lang['CONGRATULATIONS'] : '{ CONGRATULATIONS }')); ?>: <strong><?php echo (isset($this->_rootref['BIRTHDAY_LIST'])) ? $this->_rootref['BIRTHDAY_LIST'] : ''; ?></strong><?php } else { echo ((isset($this->_rootref['L_NO_BIRTHDAYS'])) ? $this->_rootref['L_NO_BIRTHDAYS'] : ((isset($user->lang['NO_BIRTHDAYS'])) ? $user->lang['NO_BIRTHDAYS'] : '{ NO_BIRTHDAYS }')); } ?></li>
	
	<li>
		<?php echo (isset($this->_rootref['TOTAL_USERS_ONLINE'])) ? $this->_rootref['TOTAL_USERS_ONLINE'] : ''; ?>

	</li>
	
<?php if ($this->_rootref['S_USER_LOGGED_IN']) {  ?>

	<li>
		<?php echo (isset($this->_rootref['LAST_VISIT_DATE'])) ? $this->_rootref['LAST_VISIT_DATE'] : ''; ?>

	</li>
<?php } ?>

		<li>
		<?php echo (isset($this->_rootref['CURRENT_TIME'])) ? $this->_rootref['CURRENT_TIME'] : ''; ?>

	</li>
<?php if ($this->_rootref['NEWEST_USER']) {  ?>

		<li>
		<?php echo (isset($this->_rootref['TOTAL_POSTS'])) ? $this->_rootref['TOTAL_POSTS'] : ''; ?> &bull; <?php echo (isset($this->_rootref['TOTAL_TOPICS'])) ? $this->_rootref['TOTAL_TOPICS'] : ''; ?> &bull; <?php echo (isset($this->_rootref['TOTAL_USERS'])) ? $this->_rootref['TOTAL_USERS'] : ''; ?>

	</li>
<li><?php echo (isset($this->_rootref['NEWEST_USER'])) ? $this->_rootref['NEWEST_USER'] : ''; ?></li>
<li><?php echo (isset($this->_rootref['RECORD_USERS'])) ? $this->_rootref['RECORD_USERS'] : ''; ?></li>
<?php } ?>

    </ul>
</div>
		                    									</div><?php } ?>

													
																																															<div id="maincontent-tm" class="png"><div id="maincontent-tl" class="png"><div id="maincontent-tr" class="png"></div></div></div>
															<div id="maincontent-m" class="png"><div id="maincontent-l" class="png"><div id="maincontent-r" class="png"><div id="maincontent-surround" class="png">
																		                    									<?php if ($this->_rootref['SHOW_REF_PATHWAY']) {  ?><div id="breadcrumbs">
																	<a href="<?php echo (isset($this->_rootref['U_INDEX'])) ? $this->_rootref['U_INDEX'] : ''; ?>" id="breadcrumbs-home" class="png"></a>
		                    										<span class="breadcrumbs pathway">
<a href="<?php echo (isset($this->_rootref['U_INDEX'])) ? $this->_rootref['U_INDEX'] : ''; ?>" accesskey="h" class="pathway"><?php echo ((isset($this->_rootref['L_INDEX'])) ? $this->_rootref['L_INDEX'] : ((isset($user->lang['INDEX'])) ? $user->lang['INDEX'] : '{ INDEX }')); ?></a> <?php $_navlinks_count = (isset($this->_tpldata['navlinks'])) ? sizeof($this->_tpldata['navlinks']) : 0;if ($_navlinks_count) {for ($_navlinks_i = 0; $_navlinks_i < $_navlinks_count; ++$_navlinks_i){$_navlinks_val = &$this->_tpldata['navlinks'][$_navlinks_i]; ?><img src="<?php echo (isset($this->_rootref['T_THEME_PATH'])) ? $this->_rootref['T_THEME_PATH'] : ''; ?>/images/arrow.png" alt=""  /><span class="no-link"><a href="<?php echo $_navlinks_val['U_VIEW_FORUM']; ?>"><?php echo $_navlinks_val['FORUM_NAME']; ?></a></span><?php }} ?></span>
</div><?php } ?>

		                    										                    												                    									<div class="bodycontent">
		                    												                    												                    										<div id="maincontent-block">
		                												
		                														                												<div class="">
	<div id="page" class="full-article">

<div id="wrap">
	<a id="top" name="top" accesskey="t"></a>
	<div id="page-header">
		
<?php if ($this->_rootref['REF_MENUPOSITION'] == (full)) {  ?>

		<div class="navbar">
			<div class="inner">

			<ul class="linklist navlinks">
				<li class="rightside"><a href="#" onclick="fontsizeup(); return false;" onkeypress="fontsizeup(); return false;" class="fontsize" title="<?php echo ((isset($this->_rootref['L_CHANGE_FONT_SIZE'])) ? $this->_rootref['L_CHANGE_FONT_SIZE'] : ((isset($user->lang['CHANGE_FONT_SIZE'])) ? $user->lang['CHANGE_FONT_SIZE'] : '{ CHANGE_FONT_SIZE }')); ?>"><?php echo ((isset($this->_rootref['L_CHANGE_FONT_SIZE'])) ? $this->_rootref['L_CHANGE_FONT_SIZE'] : ((isset($user->lang['CHANGE_FONT_SIZE'])) ? $user->lang['CHANGE_FONT_SIZE'] : '{ CHANGE_FONT_SIZE }')); ?></a></li>
				<?php if ($this->_rootref['U_EMAIL_TOPIC']) {  ?><li class="rightside"><a href="<?php echo (isset($this->_rootref['U_EMAIL_TOPIC'])) ? $this->_rootref['U_EMAIL_TOPIC'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_EMAIL_TOPIC'])) ? $this->_rootref['L_EMAIL_TOPIC'] : ((isset($user->lang['EMAIL_TOPIC'])) ? $user->lang['EMAIL_TOPIC'] : '{ EMAIL_TOPIC }')); ?>" class="sendemail"><?php echo ((isset($this->_rootref['L_EMAIL_TOPIC'])) ? $this->_rootref['L_EMAIL_TOPIC'] : ((isset($user->lang['EMAIL_TOPIC'])) ? $user->lang['EMAIL_TOPIC'] : '{ EMAIL_TOPIC }')); ?></a></li><?php } if ($this->_rootref['U_EMAIL_PM']) {  ?><li class="rightside"><a href="<?php echo (isset($this->_rootref['U_EMAIL_PM'])) ? $this->_rootref['U_EMAIL_PM'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_EMAIL_PM'])) ? $this->_rootref['L_EMAIL_PM'] : ((isset($user->lang['EMAIL_PM'])) ? $user->lang['EMAIL_PM'] : '{ EMAIL_PM }')); ?>" class="sendemail"><?php echo ((isset($this->_rootref['L_EMAIL_PM'])) ? $this->_rootref['L_EMAIL_PM'] : ((isset($user->lang['EMAIL_PM'])) ? $user->lang['EMAIL_PM'] : '{ EMAIL_PM }')); ?></a></li><?php } if ($this->_rootref['U_PRINT_TOPIC']) {  ?><li class="rightside"><a href="<?php echo (isset($this->_rootref['U_PRINT_TOPIC'])) ? $this->_rootref['U_PRINT_TOPIC'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_PRINT_TOPIC'])) ? $this->_rootref['L_PRINT_TOPIC'] : ((isset($user->lang['PRINT_TOPIC'])) ? $user->lang['PRINT_TOPIC'] : '{ PRINT_TOPIC }')); ?>" accesskey="p" class="print"><?php echo ((isset($this->_rootref['L_PRINT_TOPIC'])) ? $this->_rootref['L_PRINT_TOPIC'] : ((isset($user->lang['PRINT_TOPIC'])) ? $user->lang['PRINT_TOPIC'] : '{ PRINT_TOPIC }')); ?></a></li><?php } if ($this->_rootref['U_PRINT_PM']) {  ?><li class="rightside"><a href="<?php echo (isset($this->_rootref['U_PRINT_PM'])) ? $this->_rootref['U_PRINT_PM'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_PRINT_PM'])) ? $this->_rootref['L_PRINT_PM'] : ((isset($user->lang['PRINT_PM'])) ? $user->lang['PRINT_PM'] : '{ PRINT_PM }')); ?>" accesskey="p" class="print"><?php echo ((isset($this->_rootref['L_PRINT_PM'])) ? $this->_rootref['L_PRINT_PM'] : ((isset($user->lang['PRINT_PM'])) ? $user->lang['PRINT_PM'] : '{ PRINT_PM }')); ?></a></li><?php } ?>

			</ul>

			<?php if (! $this->_rootref['S_IS_BOT'] && $this->_rootref['S_USER_LOGGED_IN']) {  ?>

			<ul class="linklist leftside">
				<li class="icon-ucp">
					<a href="<?php echo (isset($this->_rootref['U_PROFILE'])) ? $this->_rootref['U_PROFILE'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_PROFILE'])) ? $this->_rootref['L_PROFILE'] : ((isset($user->lang['PROFILE'])) ? $user->lang['PROFILE'] : '{ PROFILE }')); ?>" accesskey="u"><?php echo ((isset($this->_rootref['L_PROFILE'])) ? $this->_rootref['L_PROFILE'] : ((isset($user->lang['PROFILE'])) ? $user->lang['PROFILE'] : '{ PROFILE }')); ?></a>
						<?php if ($this->_rootref['S_DISPLAY_PM']) {  ?> (<a href="<?php echo (isset($this->_rootref['U_PRIVATEMSGS'])) ? $this->_rootref['U_PRIVATEMSGS'] : ''; ?>"><?php echo (isset($this->_rootref['PRIVATE_MESSAGE_INFO'])) ? $this->_rootref['PRIVATE_MESSAGE_INFO'] : ''; ?></a>)<?php } ?> &bull; 
					<a href="<?php echo (isset($this->_rootref['U_SEARCH_SELF'])) ? $this->_rootref['U_SEARCH_SELF'] : ''; ?>"><?php echo ((isset($this->_rootref['L_SEARCH_SELF'])) ? $this->_rootref['L_SEARCH_SELF'] : ((isset($user->lang['SEARCH_SELF'])) ? $user->lang['SEARCH_SELF'] : '{ SEARCH_SELF }')); ?></a>
					<?php if ($this->_rootref['U_RESTORE_PERMISSIONS']) {  ?> &bull;
					<a href="<?php echo (isset($this->_rootref['U_RESTORE_PERMISSIONS'])) ? $this->_rootref['U_RESTORE_PERMISSIONS'] : ''; ?>"><?php echo ((isset($this->_rootref['L_RESTORE_PERMISSIONS'])) ? $this->_rootref['L_RESTORE_PERMISSIONS'] : ((isset($user->lang['RESTORE_PERMISSIONS'])) ? $user->lang['RESTORE_PERMISSIONS'] : '{ RESTORE_PERMISSIONS }')); ?></a>
					<?php } ?>

				</li>
			</ul>
			<?php } ?>


			<ul class="linklist rightside">
				<li class="icon-faq"><a href="<?php echo (isset($this->_rootref['U_FAQ'])) ? $this->_rootref['U_FAQ'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_FAQ_EXPLAIN'])) ? $this->_rootref['L_FAQ_EXPLAIN'] : ((isset($user->lang['FAQ_EXPLAIN'])) ? $user->lang['FAQ_EXPLAIN'] : '{ FAQ_EXPLAIN }')); ?>"><?php echo ((isset($this->_rootref['L_FAQ'])) ? $this->_rootref['L_FAQ'] : ((isset($user->lang['FAQ'])) ? $user->lang['FAQ'] : '{ FAQ }')); ?></a></li>
				<?php if (! $this->_rootref['S_IS_BOT']) {  if ($this->_rootref['S_DISPLAY_MEMBERLIST']) {  ?><li class="icon-members"><a href="<?php echo (isset($this->_rootref['U_MEMBERLIST'])) ? $this->_rootref['U_MEMBERLIST'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_MEMBERLIST_EXPLAIN'])) ? $this->_rootref['L_MEMBERLIST_EXPLAIN'] : ((isset($user->lang['MEMBERLIST_EXPLAIN'])) ? $user->lang['MEMBERLIST_EXPLAIN'] : '{ MEMBERLIST_EXPLAIN }')); ?>"><?php echo ((isset($this->_rootref['L_MEMBERLIST'])) ? $this->_rootref['L_MEMBERLIST'] : ((isset($user->lang['MEMBERLIST'])) ? $user->lang['MEMBERLIST'] : '{ MEMBERLIST }')); ?></a></li><?php } if (! $this->_rootref['S_USER_LOGGED_IN'] && $this->_rootref['S_REGISTER_ENABLED']) {  ?><li class="icon-register"><a href="<?php echo (isset($this->_rootref['U_REGISTER'])) ? $this->_rootref['U_REGISTER'] : ''; ?>"><?php echo ((isset($this->_rootref['L_REGISTER'])) ? $this->_rootref['L_REGISTER'] : ((isset($user->lang['REGISTER'])) ? $user->lang['REGISTER'] : '{ REGISTER }')); ?></a></li><?php } ?>

					<li class="icon-logout"><a href="<?php echo (isset($this->_rootref['U_LOGIN_LOGOUT'])) ? $this->_rootref['U_LOGIN_LOGOUT'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_LOGIN_LOGOUT'])) ? $this->_rootref['L_LOGIN_LOGOUT'] : ((isset($user->lang['LOGIN_LOGOUT'])) ? $user->lang['LOGIN_LOGOUT'] : '{ LOGIN_LOGOUT }')); ?>" accesskey="l"><?php echo ((isset($this->_rootref['L_LOGIN_LOGOUT'])) ? $this->_rootref['L_LOGIN_LOGOUT'] : ((isset($user->lang['LOGIN_LOGOUT'])) ? $user->lang['LOGIN_LOGOUT'] : '{ LOGIN_LOGOUT }')); ?></a></li>
				<?php } ?>

			</ul>
</div>
		</div>
		<?php } else { ?>

			<ul class="linklist ">
					<li class="rightside"><a href="#" onclick="fontsizeup(); return false;" onkeypress="fontsizeup(); return false;" class="fontsize" title="<?php echo ((isset($this->_rootref['L_CHANGE_FONT_SIZE'])) ? $this->_rootref['L_CHANGE_FONT_SIZE'] : ((isset($user->lang['CHANGE_FONT_SIZE'])) ? $user->lang['CHANGE_FONT_SIZE'] : '{ CHANGE_FONT_SIZE }')); ?>"><?php echo ((isset($this->_rootref['L_CHANGE_FONT_SIZE'])) ? $this->_rootref['L_CHANGE_FONT_SIZE'] : ((isset($user->lang['CHANGE_FONT_SIZE'])) ? $user->lang['CHANGE_FONT_SIZE'] : '{ CHANGE_FONT_SIZE }')); ?></a></li>
				<?php if ($this->_rootref['U_EMAIL_TOPIC']) {  ?><li class="rightside"><a href="<?php echo (isset($this->_rootref['U_EMAIL_TOPIC'])) ? $this->_rootref['U_EMAIL_TOPIC'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_EMAIL_TOPIC'])) ? $this->_rootref['L_EMAIL_TOPIC'] : ((isset($user->lang['EMAIL_TOPIC'])) ? $user->lang['EMAIL_TOPIC'] : '{ EMAIL_TOPIC }')); ?>" class="sendemail"><?php echo ((isset($this->_rootref['L_EMAIL_TOPIC'])) ? $this->_rootref['L_EMAIL_TOPIC'] : ((isset($user->lang['EMAIL_TOPIC'])) ? $user->lang['EMAIL_TOPIC'] : '{ EMAIL_TOPIC }')); ?></a></li><?php } if ($this->_rootref['U_EMAIL_PM']) {  ?><li class="rightside"><a href="<?php echo (isset($this->_rootref['U_EMAIL_PM'])) ? $this->_rootref['U_EMAIL_PM'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_EMAIL_PM'])) ? $this->_rootref['L_EMAIL_PM'] : ((isset($user->lang['EMAIL_PM'])) ? $user->lang['EMAIL_PM'] : '{ EMAIL_PM }')); ?>" class="sendemail"><?php echo ((isset($this->_rootref['L_EMAIL_PM'])) ? $this->_rootref['L_EMAIL_PM'] : ((isset($user->lang['EMAIL_PM'])) ? $user->lang['EMAIL_PM'] : '{ EMAIL_PM }')); ?></a></li><?php } if ($this->_rootref['U_PRINT_TOPIC']) {  ?><li class="rightside"><a href="<?php echo (isset($this->_rootref['U_PRINT_TOPIC'])) ? $this->_rootref['U_PRINT_TOPIC'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_PRINT_TOPIC'])) ? $this->_rootref['L_PRINT_TOPIC'] : ((isset($user->lang['PRINT_TOPIC'])) ? $user->lang['PRINT_TOPIC'] : '{ PRINT_TOPIC }')); ?>" accesskey="p" class="print"><?php echo ((isset($this->_rootref['L_PRINT_TOPIC'])) ? $this->_rootref['L_PRINT_TOPIC'] : ((isset($user->lang['PRINT_TOPIC'])) ? $user->lang['PRINT_TOPIC'] : '{ PRINT_TOPIC }')); ?></a></li><?php } if ($this->_rootref['U_PRINT_PM']) {  ?><li class="rightside"><a href="<?php echo (isset($this->_rootref['U_PRINT_PM'])) ? $this->_rootref['U_PRINT_PM'] : ''; ?>" title="<?php echo ((isset($this->_rootref['L_PRINT_PM'])) ? $this->_rootref['L_PRINT_PM'] : ((isset($user->lang['PRINT_PM'])) ? $user->lang['PRINT_PM'] : '{ PRINT_PM }')); ?>" accesskey="p" class="print"><?php echo ((isset($this->_rootref['L_PRINT_PM'])) ? $this->_rootref['L_PRINT_PM'] : ((isset($user->lang['PRINT_PM'])) ? $user->lang['PRINT_PM'] : '{ PRINT_PM }')); ?></a></li><?php } ?>

			</ul>
<?php } ?>

	</div>

	<a name="start_here"></a>
	<div id="page-body">
		
		 <?php if ($this->_rootref['S_BOARD_DISABLED'] && $this->_rootref['S_USER_LOGGED_IN'] && ( $this->_rootref['U_MCP'] || $this->_rootref['U_ACP'] )) {  ?> 
		<div id="message" class="rules">
			<div class="inner"><span class="corners-top"><span></span></span>
				<strong><?php echo ((isset($this->_rootref['L_INFORMATION'])) ? $this->_rootref['L_INFORMATION'] : ((isset($user->lang['INFORMATION'])) ? $user->lang['INFORMATION'] : '{ INFORMATION }')); ?>:</strong> <?php echo ((isset($this->_rootref['L_BOARD_DISABLED'])) ? $this->_rootref['L_BOARD_DISABLED'] : ((isset($user->lang['BOARD_DISABLED'])) ? $user->lang['BOARD_DISABLED'] : '{ BOARD_DISABLED }')); ?>

			<span class="corners-bottom"><span></span></span></div>
		</div>
		<?php } ?>